// flow-typed signature: 238220250dffead82724f1097a354d11
// flow-typed version: <<STUB>>/react-native-bluetooth-state_v^2.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-bluetooth-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-bluetooth-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-bluetooth-state/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-bluetooth-state/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-bluetooth-state/RNBluetoothState.android' {
  declare module.exports: any;
}

declare module 'react-native-bluetooth-state/RNBluetoothState.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-bluetooth-state/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-bluetooth-state/Example/index.android'>;
}
declare module 'react-native-bluetooth-state/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-bluetooth-state/Example/index.ios'>;
}
declare module 'react-native-bluetooth-state/RNBluetoothState.android.js' {
  declare module.exports: $Exports<'react-native-bluetooth-state/RNBluetoothState.android'>;
}
declare module 'react-native-bluetooth-state/RNBluetoothState.ios.js' {
  declare module.exports: $Exports<'react-native-bluetooth-state/RNBluetoothState.ios'>;
}
